import { useRef, useState } from 'react'
import { Bot, Check, DatabaseBackup, Download, Eye, EyeOff, KeyRound, Languages, LockKeyhole, MoonStar, Save, ShieldCheck, Sparkles, Upload, UserRound } from 'lucide-react'
import { memoryRepository } from '../services/memoryRepository'
import { useAppStore } from '../stores/appStore'
import { open, save } from '@tauri-apps/plugin-dialog'
import { isDesktop, nativeBridge } from '../services/nativeBridge'
import { useI18n } from '../i18n'

export function SettingsPage() {
  const { t } = useI18n()
  const store = useAppStore(); const [settings, setSettings] = useState(store.ai); const [apiKey, setApiKey] = useState(''); const [showKey, setShowKey] = useState(false); const [notice, setNotice] = useState(''); const importRef = useRef<HTMLInputElement>(null)
  const saveAi = async () => { const next={ ...settings, hasApiKey: settings.hasApiKey || !!apiKey }; if(isDesktop()) await nativeBridge.configureAi(next,apiKey||undefined); store.setAi(next); setNotice(t('AI 配置已封存', 'AI settings saved')); setTimeout(() => setNotice(''), 2000) }
  const backup = async () => { if (isDesktop()) { const path = await save({ defaultPath: `pensieve-${new Date().toISOString().slice(0,10)}.pensieve`, filters: [{ name: 'Pensieve 加密备份', extensions: ['pensieve'] }] }); if (!path) return; const password = window.prompt('请为这份备份设置独立密码（至少 8 位）') || ''; if (password.length < 8) { setNotice('备份密码至少需要 8 位'); return } await nativeBridge.exportBackup(path, password); setNotice('加密记忆备份已导出'); return } const blob = new Blob([memoryRepository.exportAll()], { type: 'application/json' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `pensieve-${new Date().toISOString().slice(0,10)}.pensieve`; a.click(); URL.revokeObjectURL(url); setNotice('记忆备份已导出') }
  const restore = async (file?: File) => { try { if(isDesktop()){const path=await open({multiple:false,filters:[{name:'Pensieve 加密备份',extensions:['pensieve']}]});if(!path)return;const password=window.prompt('请输入这份备份的独立密码')||'';await nativeBridge.restoreBackup(path,password);setNotice('记忆已恢复，请重新解锁');setTimeout(store.lock,900);return} if (!file) return; memoryRepository.importAll(await file.text()); setNotice('记忆已从备份中苏醒') } catch (e) { setNotice(e instanceof Error ? e.message : '导入失败') } }
  return <div className="page settings-page"><header className="page-header"><div className="eyebrow"><Sparkles size={14} /> SANCTUARY SETTINGS</div><h1>{t('偏好与守护', 'Preferences & Protection')}</h1><p>{t('照顾记忆的方式，也应该由你决定。', 'How your memories are cared for should be your choice.')}</p></header>{notice && <div className="toast"><Check /> {notice}</div>}
    <div className="settings-grid"><section className="settings-card"><div className="settings-heading"><span><MoonStar /></span><div><h2>{t('氛围与感受', 'Atmosphere')}</h2><p>{t('让冥想盆以舒服的节奏呼吸', 'Let the basin breathe at a comfortable pace')}</p></div></div><SettingToggle label={t('减少动态效果', 'Reduce motion')} note={t('减弱水波、雾气与星粒子动画', 'Soften ripples, mist and starlight animations')} checked={store.reduceMotion} onChange={v => store.setPreference({ reduceMotion: v })} /><SettingToggle label={t('轻柔环境音', 'Gentle ambience')} note={t('存入与沉浸时播放短暂提示音', 'Play a soft chime while storing and immersing')} checked={store.soundEnabled} onChange={v => store.setPreference({ soundEnabled: v })} /></section>
      <section className="settings-card"><div className="settings-heading"><span><UserRound /></span><div><h2>{t('你的称呼', 'Your name')}</h2><p>{t('决定冥想盆在问候时如何称呼你', 'Choose how the basin greets you')}</p></div></div><label className="profile-name-field">{t('显示名称', 'Display name')}<input value={store.displayName} maxLength={24} onChange={e => store.setDisplayName(e.target.value)} placeholder={t('留空时使用通用问候', 'Leave blank for a neutral greeting')} /></label></section>
      <section className="settings-card"><div className="settings-heading"><span><Languages /></span><div><h2>{t('界面语言', 'Interface language')}</h2><p>{t('选择冥想盆与你交谈的语言', 'Choose the language spoken by the basin')}</p></div></div><div className="language-picker" role="group" aria-label={t('界面语言', 'Interface language')}><button className={store.language === 'zh' ? 'active' : ''} onClick={() => store.setLanguage('zh')}>中文</button><button className={store.language === 'en' ? 'active' : ''} onClick={() => store.setLanguage('en')}>English</button></div></section>
      <section className="settings-card"><div className="settings-heading"><span><LockKeyhole /></span><div><h2>{t('私人记忆库', 'Private memory vault')}</h2><p>{t('此设备上的守护状态', 'Protection status on this device')}</p></div></div><div className="security-status"><ShieldCheck /><div><strong>{t('本地守护已开启', 'Local protection is active')}</strong><p>{t('应用 PIN 正在保护进入记忆库的入口', 'Your PIN guards the entrance to the vault')}</p></div></div><button className="secondary-button" onClick={store.lock}><KeyRound /> {t('立即锁定', 'Lock now')}</button></section>
      <section className="settings-card wide"><div className="settings-heading"><span><Bot /></span><div><h2>{t('冥想盆的智慧', 'Basin intelligence')}</h2><p>{t('连接兼容服务，让图片、声音与文字彼此呼应', 'Connect a compatible service to understand images, sound and text')}</p></div><SettingToggle label={t('启用 AI 整理', 'Enable AI organization')} note="" checked={settings.enabled} onChange={v => setSettings({ ...settings, enabled: v })} /></div><div className="settings-form"><label>{t('兼容 API 地址', 'Compatible API URL')}<input value={settings.baseUrl} onChange={e => setSettings({ ...settings, baseUrl: e.target.value })} /></label><label>{t('API 密钥', 'API key')}<div className="secret-input"><input type={showKey ? 'text' : 'password'} value={apiKey} onChange={e => setApiKey(e.target.value)} placeholder={settings.hasApiKey ? t('已安全保存 · 输入可替换', 'Saved securely · type to replace') : 'sk-…'} /><button onClick={() => setShowKey(!showKey)}>{showKey ? <EyeOff /> : <Eye />}</button></div></label><label>{t('整理模型', 'Organization model')}<input value={settings.chatModel} onChange={e => setSettings({ ...settings, chatModel: e.target.value })} /></label><label>{t('向量模型', 'Embedding model')}<input value={settings.embeddingModel} onChange={e => setSettings({ ...settings, embeddingModel: e.target.value })} /></label><label>{t('转写模型', 'Transcription model')}<input value={settings.transcriptionModel} onChange={e => setSettings({ ...settings, transcriptionModel: e.target.value })} /></label></div><div className="settings-actions"><span>{t('密钥在桌面版中交由系统凭据保管', 'The desktop app stores your key in system credentials')}</span><button className="primary-button" onClick={saveAi}><Save /> {t('保存连接', 'Save connection')}</button></div></section>
      <section className="settings-card wide"><div className="settings-heading"><span><DatabaseBackup /></span><div><h2>{t('备份与迁移', 'Backup & migration')}</h2><p>{t('带走属于你的每一缕记忆', 'Take every memory with you')}</p></div></div><div className="backup-actions"><button onClick={backup}><Download /><strong>{t('导出记忆备份', 'Export memory backup')}</strong><span>{t('记忆、线索与媒体清单', 'Memories, clues and media')}</span></button><button onClick={() => isDesktop() ? void restore() : importRef.current?.click()}><Upload /><strong>{t('从备份中恢复', 'Restore from backup')}</strong><span>{t('导入 .pensieve 文件', 'Import a .pensieve file')}</span></button><input ref={importRef} hidden type="file" accept=".pensieve" onChange={e => restore(e.target.files?.[0])} /></div></section></div>
  </div>
}
function SettingToggle({ label, note, checked, onChange }: { label: string; note: string; checked: boolean; onChange: (value: boolean) => void }) { return <div className="setting-row"><div><strong>{label}</strong>{note && <p>{note}</p>}</div><button aria-label={label} className={`switch ${checked ? 'on' : ''}`} onClick={() => onChange(!checked)}><i /></button></div> }
