import { useRef, useState } from 'react'
import { Bot, Check, DatabaseBackup, Download, Eye, EyeOff, KeyRound, Languages, LockKeyhole, MoonStar, Save, ShieldCheck, Sparkles, Upload, UserRound } from 'lucide-react'
import { memoryRepository } from '../services/memoryRepository'
import { useAppStore } from '../stores/appStore'
import { open, save } from '@tauri-apps/plugin-dialog'
import { isDesktop, nativeBridge } from '../services/nativeBridge'
import { useI18n } from '../i18n'

export function SettingsPage() {
  const { t } = useI18n()
  const store = useAppStore(); const [settings, setSettings] = useState(store.ai); const [apiKey, setApiKey] = useState(''); const [showKey, setShowKey] = useState(false); const [notice, setNotice] = useState(''); const importRef = useRef<HTMLInputElement>(null)
  const saveAi = async () => { const next={ ...settings, hasApiKey: settings.hasApiKey || !!apiKey }; if(isDesktop()) await nativeBridge.configureAi(next,apiKey||undefined); store.setAi(next); setNotice(t('AI 配置已封存', 'AI settings saved')); setTimeout(() => setNotice(''), 2000) }
  const backup = async () => { if (isDesktop()) { const path = await save({ defaultPath: `pensieve-${new Date().toISOString().slice(0,10)}.pensieve`, filters: [{ name: 'Pensieve 加密备份', extensions: ['pensieve'] }] }); if (!path) return; const password = window.prompt('请为这份备份设置独立密码（至少 8 位）') || ''; if (password.length < 8) { setNotice('备份密码至少需要 8 位'); return } await nativeBridge.exportBackup(path, password); setNotice('加密记忆备份已导出'); return } const blob = new Blob([memoryRepository.exportAll()], { type: 'application/json' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `pensieve-${new Date().toISOString().slice(0,10)}.pensieve`; a.click(); URL.revokeObjectURL(url); setNotice('记忆备份已导出') }
  const restore = async (file?: File) => { try { if(isDesktop()){const path=await open({multiple:false,filters:[{name:'Pensieve 加密备份',extensions:['pensieve']}]});if(!path)return;const password=window.prompt(t('请输入这份备份的独立密码', 'Enter this backup’s password'))||'';await nativeBridge.restoreBackup(path,password);setNotice(t('星河已迁入，请使用原记忆库 PIN 唤醒', 'Constellation restored. Awaken it with the source vault PIN'));setTimeout(store.lock,900);return} if (!file) return; memoryRepository.importAll(await file.text()); setNotice(t('记忆已从备份中苏醒', 'Memories restored from backup')) } catch (e) { setNotice(e instanceof Error ? e.message : t('导入失败', 'Import failed')) } }
  return <div className="page settings-page"><header className="page-header sanctuary-header"><div className="eyebrow"><Sparkles size={14} /> {t('静谧结界', 'SANCTUARY')}</div><h1>{t('偏好与守护', 'Preferences & Protection')}</h1></header>{notice && <div className="toast"><Check /> {notice}</div>}
    <div className="settings-grid"><section className="settings-card"><div className="settings-heading"><span><MoonStar /></span><h2>{t('氛围', 'Atmosphere')}</h2></div><SettingToggle label={t('静谧水面', 'Still water')} checked={store.reduceMotion} onChange={v => store.setPreference({ reduceMotion: v })} /><SettingToggle label={t('水下回声', 'Underwater echoes')} checked={store.soundEnabled} onChange={v => store.setPreference({ soundEnabled: v })} /></section>
      <section className="settings-card"><div className="settings-heading"><span><UserRound /></span><h2>{t('称呼', 'Name')}</h2></div><label className="profile-name-field">{t('你的名字', 'Your name')}<input value={store.displayName} maxLength={24} onChange={e => store.setDisplayName(e.target.value)} /></label></section>
      <section className="settings-card"><div className="settings-heading"><span><Languages /></span><h2>{t('语言', 'Language')}</h2></div><div className="language-picker" role="group" aria-label={t('界面语言', 'Interface language')}><button className={store.language === 'zh' ? 'active' : ''} onClick={() => store.setLanguage('zh')}>中文</button><button className={store.language === 'en' ? 'active' : ''} onClick={() => store.setLanguage('en')}>English</button></div></section>
      <section className="settings-card"><div className="settings-heading"><span><LockKeyhole /></span><h2>{t('守护', 'Protection')}</h2></div><div className="security-status"><ShieldCheck /><strong>{t('本地守护已开启', 'Local protection is active')}</strong></div><button className="secondary-button" onClick={store.lock}><KeyRound /> {t('锁定', 'Lock')}</button></section>
      <section className="settings-card wide"><div className="settings-heading"><span><Bot /></span><h2>{t('冥想盆的智慧', 'Basin intelligence')}</h2><SettingToggle label={t('唤醒', 'Awaken')} checked={settings.enabled} onChange={v => setSettings({ ...settings, enabled: v })} /></div><div className="settings-form"><label>{t('回响入口', 'Echo gateway')}<input value={settings.baseUrl} onChange={e => setSettings({ ...settings, baseUrl: e.target.value })} /></label><label>{t('密钥', 'Key')}<div className="secret-input"><input type={showKey ? 'text' : 'password'} value={apiKey} onChange={e => setApiKey(e.target.value)} placeholder={settings.hasApiKey ? t('已封存', 'Sealed') : ''} /><button aria-label={t('显示密钥', 'Show key')} onClick={() => setShowKey(!showKey)}>{showKey ? <EyeOff /> : <Eye />}</button></div></label><label>{t('整理', 'Organize')}<input value={settings.chatModel} onChange={e => setSettings({ ...settings, chatModel: e.target.value })} /></label><label>{t('寻觅', 'Seek')}<input value={settings.embeddingModel} onChange={e => setSettings({ ...settings, embeddingModel: e.target.value })} /></label><label>{t('聆听', 'Listen')}<input value={settings.transcriptionModel} onChange={e => setSettings({ ...settings, transcriptionModel: e.target.value })} /></label></div><div className="settings-actions"><button className="primary-button" onClick={saveAi}><Save /> {t('封存连接', 'Seal connection')}</button></div></section>
      <section className="settings-card wide"><div className="settings-heading"><span><DatabaseBackup /></span><h2>{t('迁徙', 'Migration')}</h2></div><div className="backup-actions"><button onClick={backup}><Download /><strong>{t('带走所有回响', 'Carry every echo')}</strong></button><button onClick={() => isDesktop() ? void restore() : importRef.current?.click()}><Upload /><strong>{t('唤醒旧日星河', 'Awaken an old constellation')}</strong></button><input ref={importRef} hidden type="file" accept=".pensieve" onChange={e => restore(e.target.files?.[0])} /></div></section></div>
  </div>
}
function SettingToggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) { return <div className="setting-row"><strong>{label}</strong><button aria-label={label} className={`switch ${checked ? 'on' : ''}`} onClick={() => onChange(!checked)}><i /></button></div> }
